- name: Setup my development environment
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu machines
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary applications
      ansible.builtin.apt:
        name:
          - git
          - build-essential
          - zsh
          - alacritty
          - neovim
          - ripgrep
          - fd-find
          - fzf
          - zoxide
        state: present

    - name: Install Oh My Zsh # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: Install zsh-completions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1

    - name: Install autoupdate-zsh-plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
        dest: ~/.oh-my-zsh/custom/plugins/autoupdate
        depth: 1

    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Check effective user
      command: whoami
      register: whoami

    - name: Show whoami
      debug:
        msg: "Running as user {{ whoami.stdout }}"

    - name: Show ansible user
      debug:
        msg: "Running as user {{ ansible_user_id }}"
