- name: Setup Linux Desktop with Oh My Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu machines
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary applications
      ansible.builtin.apt:
        name:
          - git
          - build-essential
          - zsh
          - alacritty
          - neovim
        state: present

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh

    - name: Run Oh My Zsh installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
