- name: Setup Linux Desktop with Oh My Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu machines
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary applications
      ansible.builtin.apt:
        name:
          - git
          - build-essential
          - zsh
          - alacritty
          - neovim
        state: present

    - name: Install Oh My Zsh for the current user
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: Clone zsh-autosuggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: Configure .zshrc to use plugin
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        insertafter: '^plugins=\('
        line: "  zsh-autosuggestions"
        state: present
    - name: Set default shell to Zsh for the specified user
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: "/bin/zsh"
