- name: Setup my development environment
  hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu machines
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary applications
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - unzip
          - curl
          - polybar
          - feh
          - picom
          - stow
          - solaar
          - build-essential
          - zsh
          # - alacritty
          - neovim
          - ripgrep
          - fd-find
          - fzf
          - zoxide
          - btop
          - rofi
        state: present

    - name: Run zsh install
      ansible.builtin.include_tasks:
        file: ./tasks/zsh.yml

    - name: Download dotfiles repo # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/guilhermetk/dotfiles.git
        dest: ~/dotfiles
        depth: 1
        force: true

    - name: Install dotfiles
      ansible.builtin.command:
        cmd: stow .
        chdir: ~/dotfiles

    # Install nerd fonts
    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Font exists
      become: true
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/FiraCode-Regular.ttf"
      register: font_exists
      ignore_errors: yes

    - name: Download Hack
      when: font_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    # Install brave browser
    - name: Check if keyring exists
      ansible.builtin.stat:
        path: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      register: keyring_file

    - name: Get keyring file
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
        mode: "0644"
      when: not keyring_file.stat.exists
      become: true

    - name: Add Brave repository to list of repositories
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/brave-browser-release.list
        content: |
          deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        mode: "0644"

    - name: Install Brave
      ansible.builtin.apt:
        name: brave-browser
        state: present
        update_cache: true
      become: true

    # Install slack via snap
    - name: Install Slack
      become: true
      ansible.builtin.command:
        cmd: sudo snap install slack

    # Install 1password via deb
    - name: Install 1Password
      become: true
      ansible.builtin.apt:
        deb: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
        state: present

    # - name: Install nvm
    #   ansible.builtin.shell: >
    #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    #   args:
    #     creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
