- name: Setup my development environment
  hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu machines
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary applications
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - curl
          - polybar
          - feh
          - picom
          - stow
          - solaar
          - build-essential
          - zsh
          # - alacritty
          - neovim
          - ripgrep
          - fd-find
          - fzf
          - zoxide
          - btop
          - rofi
        state: present

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh

    - name: Run Oh My Zsh installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: Install zsh-completions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1

    - name: Install autoupdate-zsh-plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
        dest: ~/.oh-my-zsh/custom/plugins/autoupdate
        depth: 1

    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Download dotfiles repo # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/guilhermetk/dotfiles.git
        dest: ~/dotfiles
        depth: 1
        force: true

    - name: Install dotfiles
      ansible.builtin.command:
        cmd: stow .
        chdir: ~/dotfiles

    # Install nerd fonts
    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Font exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Fira*Code"
      register: font_exists
      ignore_errors: yes

    - name: Download Hack
      when: font_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    # Install brave browser
    - name: Check if keyring exists
      ansible.builtin.stat:
        path: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      register: keyring_file

    - name: Get keyring file
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
        mode: "0644"
      when: not keyring_file.stat.exists
      become: true

    - name: Add Brave repository to list of repositories
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/brave-browser-release.list
        content: |
          deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        mode: "0644"

    - name: Install Brave
      ansible.builtin.apt:
        name: brave-browser
        state: present
        update_cache: true
      become: true

    # Install slack via snap
    - name: Install Slack
      community.general.snap:
        name: slack
        dangerous: true
        classic: true
        state: present

    # - name: Install nvm
    #   ansible.builtin.shell: >
    #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    #   args:
    #     creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
