- name: Setup my development environment
  hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu machines
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary applications
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - unzip
          - curl
          - polybar
          - kitty
          - feh
          - picom
          - stow
          - solaar
          - build-essential
          - zsh
          - neovim
          - ripgrep
          - fd-find
          - fzf
          - zoxide
          - btop
          - rofi
        state: present

    - name: Run zsh install
      tags: zsh
      ansible.builtin.include_tasks:
        file: ./tasks/zsh.yml

    - name: Run dotfiles install
      tags: dotfiles
      ansible.builtin.include_tasks:
        file: ./tasks/dotfiles.yml

    - name: Run fonts install
      tags: fonts
      ansible.builtin.include_tasks:
        file: ./tasks/fonts.yml

    - name: Run github cli install
      tags: githubcli
      ansible.builtin.include_tasks:
        file: ./tasks/github-client.yml

    - name: Run brave install
      tags: brave
      ansible.builtin.include_tasks:
        file: ./tasks/brave.yml

    - name: Run slack install
      tags: slack
      ansible.builtin.include_tasks:
        file: ./tasks/slack.yml

    - name: Run 1password install
      tags: 1password
      ansible.builtin.include_tasks:
        file: ./tasks/1password.yml

    - name: Run node install
      tags: node
      ansible.builtin.include_tasks:
        file: ./tasks/node.yml

