- name: Download dotfiles repo # noqa: latest
  tags: dotfiles
  ansible.builtin.git:
    repo: https://github.com/guilhermetk/dotfiles.git
    dest: ~/dotfiles
    depth: 1
    force: true

- name: Install dotfiles
  tags: dotfiles
  ansible.builtin.command:
    cmd: stow .
    chdir: ~/dotfiles
