# Install nerd fonts
- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Font exists
  become: true
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/FiraCode-Regular.ttf"
  register: font_exists
  ignore_errors: yes

- name: Download Hack
  when: font_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
